### ISSUE TITLE
我想在一页当中增加按钮，配置文件该怎么写，对不起问了个非常基础的问题

### ISSUE THREAD

**Issue by FacialLIM** [PayaHai/DMenu#4]
我想在一页当中增加按钮，配置文件格式是什么，对不起问了个非常基础的问题

**Comment by PayaHai** [comment]
没有关系

在安装插件后您可以在`plugins/DMenu`下看到示例的文件
文件内有详细的注释，您可以根据注释进行配置
如有任何问题欢迎提问

此外，您可以在插件交流群[674416045]中提问，以获得更加及时的帮助

**Comment by FacialLIM** [comment]
请问一下，我想像您发在minebbs的图片一样，在同一页当中添加多个按钮，我该如何进行配置，在您的注释当中没有看到类似的说明，所以想在这里问您

**Comment by PayaHai** [comment]
这是拥有两个按钮的页面配置文件:
```yaml
name: 主菜单
# 菜单名称

content: "§7Hi! \n欢迎回来!"
# 菜单内容

buttons:
    # 按钮
    -
        name: 前往测试菜单
        # 按钮名称

        run: cs
        # 点击按钮执行的内容
        # 如果按钮类型为 cmd 或 console_cmd 则填写需要玩家执行的命令（无需/）
        # 如果按钮类型为 form 则填写要打开页面的文件名称 (去.yml后缀)

        type: form
        # 点击按钮执行操作的类型，可选：cmd console_cmd form
        # cmd：让玩家执行命令
        # console_cmd：后台执行命令
        # form：打开一个表单

        visible: all
        # 可见客户端类型，可选：all be je
        # all：所有玩家可见
        # be：仅 BE 玩家可见
        # je：仅 JE 玩家可见

        isOp: false
        # 仅 Op 可见

        Je:
            # Je 玩家按钮
            # Java 版玩家 UI 中的按钮
            type: "grass_block"
            # 按钮物品类型,MC 标准类名，不要带 “minecraft:”
            lore:
                # 按钮的描述
                - "§7点我前往测试菜单"

        Be:
            # Be 玩家按钮
            path: textures/ui/icon_recipe_nature.png
            # 基岩版玩家 UI 中的按钮图标 （本地材质）
            url: https://avatars.githubusercontent.com/u/142202241
            # 基岩版玩家 UI 中的按钮图标 （链接），如果 path 和 url 都填写，则优先使用 path，如两个参数否不存在则为纯文本按钮
    -
        name: 前往测试菜单
        # 按钮名称

        run: cs
        # 点击按钮执行的内容
        # 如果按钮类型为 cmd 或 console_cmd 则填写需要玩家执行的命令（无需/）
        # 如果按钮类型为 form 则填写要打开页面的文件名称 (去.yml后缀)

        type: form
        # 点击按钮执行操作的类型，可选：cmd console_cmd form
        # cmd：让玩家执行命令
        # console_cmd：后台执行命令
        # form：打开一个表单

        visible: all
        # 可见客户端类型，可选：all be je
        # all：所有玩家可见
        # be：仅 BE 玩家可见
        # je：仅 JE 玩家可见

        isOp: false
        # 仅 Op 可见

        Je:
            # Je 玩家按钮
            # Java 版玩家 UI 中的按钮
            type: "grass_block"
            # 按钮物品类型,MC 标准类名，不要带 “minecraft:”
            lore:
                # 按钮的描述
                - "§7点我前往测试菜单"

        Be:
            # Be 玩家按钮
            path: textures/ui/icon_recipe_nature.png
            # 基岩版玩家 UI 中的按钮图标 （本地材质）
            url: https://avatars.githubusercontent.com/u/142202241
            # 基岩版玩家 UI 中的按钮图标 （链接），如果 path 和 url 都填写，则优先使用 path，如两个参数否不存在则为纯文本按钮
```
这是我服务器的配置文件(去除了注释)
```yaml
name: §l§bD§cZ§aD§dG§ea§bm§ce

buttons:
    -
        name: 传送
        run: dtp
        type: cmd
        visible: all
        isOp: false
        Je:
            type: "piston"
            lore:
                - "§7传送菜单"
        Be:
            path: textures/ui/icon_saleribbon.png
    -
        name: 成就
        run: geyser advancements
        type: cmd
        visible: be
        isOp: false
        Be:
            path: textures/ui/warning_alex.png
    -
        name: 主副手物品置换
        run: geyser offhand
        type: cmd
        visible: be
        isOp: false
        Be:
            path: textures/ui/hammer_l.png
    -
        name: 自杀
        run: suicide
        type: cmd
        visible: all
        isOp: false
        Je:
            type: "netherite_sword"
            lore:
        Be:
            path: textures/ui/ErrorGlyph_small_hover.png
```
