### ISSUE TITLE
增加权限节点支持

### ISSUE THREAD

**Issue by kdxhub** [PayaHai/DMenu#8]
如题增加权限节点支持：

## 支持权限节点控制菜单能否被打开
例如菜单文件`a.yml`，可以设置权限节点`dmenu.menu.a`（示例）以控制能否打开：没有此权限节点/权限被拒绝则无法打开菜单`a.yml`

## 支持按权限节点显示菜单内容
菜单内按钮允许设置可选的权限标识符，例如：

```yml
  -
    xxxxx:
    permission: abc
```

若玩家缺失/被拒绝权限`dmenu.btn.abc`（示例）则无法展示此按钮
